version: '3.4'
services:
  web:
    container_name: pyasms
    build:
      context: app/.
      dockerfile: api-Dockerfile 
    networks: 
      mynet:
        ipv4_address: 172.19.0.2
    ports:
      - "5000:5000"
    depends_on: 
      - mysql
      - html
  mysql:
    image: "mysql:5.6"
    container_name: asms_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  html:
    container_name: asms
    build:
      context: nginx/.
      dockerfile: html-Dockerfile 
    ports:
      - "8083:80"

networks:
  mynet:
    ipam:
      config:
        - subnet: 172.19.0.0/16